CREATE SEQUENCE person_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

CREATE TABLE IF NOT EXISTS person (
    id BIGINT NOT NULL DEFAULT nextval('person_seq') PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    age INT NOT NULL
);
